<?php
// $Id: excerpt.module,v 1.6.4.3 2008/03/27 11:34:50 smk Exp $

/**
 * Implementation of hook_nodeapi().
 */
function excerpt_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if (variable_get('excerpt_'. $node->type, 1)) {
    switch ($op) {
      case 'submit':
        // Due to the presence of the teaser field in the node form,
        // node.module doesn't generate a teaser from the body upon submit.
        // In case the field has been left empty, it's up to us to generate one.
        if (trim($node->teaser) == '') {
          $node->teaser = isset($node->body) ? node_teaser($node->body, isset($node->format) ? $node->format : NULL) : '';
        }
        break;

      case 'load':
        // Support for nodes saved with earlier versions of excerpt. The teaser
        // will now be created when submitting the node form to take some load
        // from the server.
        if (trim($node->teaser) == '' && $node->body != '') {
          $node->teaser = node_teaser($node->body, isset($node->format) ? $node->format : NULL);
        }
        // node.module just checks whether the length of the teaser is less
        // than the body length to decide whether a "read more" link is to be
        // shown. With excerpts however, teasers can be even longer than the
        // body field, which is why we need to overwrite that property with our
        // own condition.
        return array('excerpt' => (bool)strcmp($node->teaser, $node->body));

      case 'view':
        $node->readmore = $node->excerpt;
        break;
    }
  }
}

/**
 * Implementation of hook_form_alter().
 */
function excerpt_form_alter($form_id, &$form) {
  if ($form_id == 'node_type_form' && isset($form['identity']['type'])) {
    $form['workflow']['excerpt'] = array(
      '#type' => 'fieldset',
      '#title' => t('Excerpt'),
      '#weight' => 0,
    );
    $form['workflow']['excerpt']['excerpt'] = array(
      '#type' => 'radios',
      '#title' => t('Teaser'),
      '#default_value' => variable_get('excerpt_'. $form['#node_type']->type, 1),
      '#options' => array(t('Auto-generated'), t('Manual excerpt')),
      '#description' => t('Choose whether the node teaser must be generated automatically or manually entered by the author.'),
    );
    $form['workflow']['excerpt']['excerpt_wt'] = array(
      '#type' => 'weight',
      '#title' => t('Weight of Teaser field'),
      '#default_value' => variable_get('excerpt_wt_'. $form['#node_type']->type, 0),
    );
  }
  else if (isset($form['type']) && $form['type']['#value'] .'_node_form' == $form_id && variable_get('excerpt_'. $form['type']['#value'], 1)) {
    $form['teaser'] = array(
      '#type' => 'textarea',
      '#title' => t('Teaser'),
      '#default_value' => $form['#node']->teaser,
      '#cols' => 60,
      '#rows' => 6,
      '#weight' => variable_get('excerpt_wt_'. $form['type']['#value'], 0),
      '#description' => t('Enter an excerpt for this item. It will be shown on listing pages along with a <em>read more</em> link which leads to the full view. Leave empty to auto-generate one from the body.'),
    );
  }
}
